JobmanagerAdminBundle_homepage:
    pattern: /
    defaults: { _controller: JobmanagerAdminBundle:Admin:index }
    requirements:
        _method: GET

jobmanager_importdb:
    pattern: /import-db
    defaults: { _controller: JobmanagerAdminBundle:Admin:updateDb }

jobmanager_getremixjobs:
    pattern: /get-remixjobs
    defaults: { _controller: JobmanagerAdminBundle:Admin:getRemixjobsNewJobs }


# job CRUD

admin_job_index:
    pattern: /job
    defaults: { _controller: JobmanagerAdminBundle:Job:index }

admin_job_view:
    path: /job/{id}
    defaults: { _controller: JobmanagerAdminBundle:Job:view }

admin_job_create:
    pattern: /job-create
    defaults: { _controller: JobmanagerAdminBundle:Job:create }

admin_job_edit:
    path: /job-edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:Job:edit }
    requirements:
        id: \d+

admin_job_delete:
    path: /job-delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:Job:delete }
    requirements:
        id: \d+


# company CRUD

admin_company_index:
    pattern: /company
    defaults: { _controller: JobmanagerAdminBundle:Company:index }

admin_company_view:
    path: /company/{id}
    defaults: { _controller: JobmanagerAdminBundle:Company:view }

admin_company_create:
    pattern: /company-create
    defaults: { _controller: JobmanagerAdminBundle:Company:create }

admin_company_edit:
    path: /company-edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:Company:edit }
    requirements:
        id: \d+

admin_company_delete:
    path: /company-delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:Company:delete }
    requirements:
        id: \d+