JobmanagerAdminBundle_homepage:
    pattern: /
    defaults: { _controller: JobmanagerAdminBundle:Admin:index }
    requirements:
        _method: GET

jobmanager_importdb:
    pattern: /import-db
    defaults : { _controller: JobmanagerAdminBundle:Admin:updateDb }

jobmanager_getremixjobs:
    pattern: /get-remixjobs
    defaults : { _controller: JobmanagerAdminBundle:Admin:getRemixjobsNewJobs }



# job CRUD

admin_job_index:
    pattern: /job
    defaults : { _controller: JobmanagerAdminBundle:Job:create }

admin_job_view:
    path: /job/{id}
    defaults: { _controller: JobmanagerAdminBundle:Job:view }

admin_job_add:
    pattern: /job/add
    defaults : { _controller: JobmanagerAdminBundle:Job:add }

admin_job_edit:
    path: /job/edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:Job:edit }
    requirements:
        id: \d+

admin_job_delete:
    path: /job/delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:Job:delete }
    requirements:
        id: \d+