JobmanagerAdminBundle_homepage:
    pattern: /
    defaults: { _controller: JobmanagerAdminBundle:Admin:index }
    requirements:
        _method: GET

jobmanager_importdb:
    pattern: /import-db
    defaults: { _controller: JobmanagerAdminBundle:Admin:updateDb }

jobmanager_getremixjobs:
    pattern: /get-remixjobs
    defaults: { _controller: JobmanagerAdminBundle:Admin:getRemixjobsNewJobs }


# job CRUD

admin_job_index:
    pattern: /job
    defaults: { _controller: JobmanagerAdminBundle:Job:index }

admin_job_view:
    path: /job/{id}
    defaults: { _controller: JobmanagerAdminBundle:Job:view }

admin_job_create:
    pattern: /job-create
    defaults: { _controller: JobmanagerAdminBundle:Job:create }

admin_job_edit:
    path: /job-edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:Job:edit }
    requirements:
        id: \d+

admin_job_delete:
    path: /job-delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:Job:delete }
    requirements:
        id: \d+


# company CRUD

admin_company_index:
    pattern: /company
    defaults: { _controller: JobmanagerAdminBundle:Company:index }

admin_company_view:
    path: /company/{id}
    defaults: { _controller: JobmanagerAdminBundle:Company:view }

admin_company_create:
    pattern: /company-create
    defaults: { _controller: JobmanagerAdminBundle:Company:create }

admin_company_edit:
    path: /company-edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:Company:edit }
    requirements:
        id: \d+

admin_company_delete:
    path: /company-delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:Company:delete }
    requirements:
        id: \d+
      
        
# recruiter CRUD

admin_recruiter_index:
    pattern: /recruiter
    defaults: { _controller: JobmanagerAdminBundle:Recruiter:index }

admin_recruiter_view:
    path: /recruiter/{id}
    defaults: { _controller: JobmanagerAdminBundle:Recruiter:view }

admin_recruiter_create:
    pattern: /recruiter-create
    defaults: { _controller: JobmanagerAdminBundle:Recruiter:create }

admin_recruiter_edit:
    path: /recruiter-edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:Recruiter:edit }
    requirements:
        id: \d+

admin_recruiter_delete:
    path: /recruiter-delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:Recruiter:delete }
    requirements:
        id: \d+
        
        
# candidate CRUD

admin_candidate_index:
    pattern: /candidate
    defaults: { _controller: JobmanagerAdminBundle:Candidate:index }

admin_candidate_view:
    path: /candidate/{id}
    defaults: { _controller: JobmanagerAdminBundle:Candidate:view }

admin_candidate_create:
    pattern: /candidate-create
    defaults: { _controller: JobmanagerAdminBundle:Candidate:create }

admin_candidate_edit:
    path: /candidate-edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:Candidate:edit }
    requirements:
        id: \d+

admin_candidate_delete:
    path: /candidate-delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:Candidate:delete }
    requirements:
        id: \d+
        
        
# competence CRUD

admin_competence_index:
    pattern: /competence
    defaults: { _controller: JobmanagerAdminBundle:Competence:index }

admin_competence_view:
    path: /competence/{id}
    defaults: { _controller: JobmanagerAdminBundle:Competence:view }

admin_competence_create:
    pattern: /competence-create
    defaults: { _controller: JobmanagerAdminBundle:Competence:create }

admin_competence_edit:
    path: /competence-edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:Competence:edit }
    requirements:
        id: \d+

admin_competence_delete:
    path: /competence-delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:Competence:delete }
    requirements:
        id: \d+


# language CRUD

admin_language_index:
    pattern: /language
    defaults: { _controller: JobmanagerAdminBundle:Language:index }

admin_language_view:
    path: /language/{id}
    defaults: { _controller: JobmanagerAdminBundle:Language:view }

admin_language_create:
    pattern: /language-create
    defaults: { _controller: JobmanagerAdminBundle:Language:create }

admin_language_edit:
    path: /language-edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:Language:edit }
    requirements:
        id: \d+

admin_language_delete:
    path: /language-delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:Language:delete }
    requirements:
        id: \d+
        
        
# diploma CRUD

admin_diploma_index:
    pattern: /diploma
    defaults: { _controller: JobmanagerAdminBundle:Diploma:index }

admin_diploma_view:
    path: /diploma/{id}
    defaults: { _controller: JobmanagerAdminBundle:Diploma:view }

admin_diploma_create:
    pattern: /diploma-create
    defaults: { _controller: JobmanagerAdminBundle:Diploma:create }

admin_diploma_edit:
    path: /diploma-edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:Diploma:edit }
    requirements:
        id: \d+

admin_diploma_delete:
    path: /diploma-delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:Diploma:delete }
    requirements:
        id: \d+
        
        
# formation CRUD

admin_formation_index:
    pattern: /formation
    defaults: { _controller: JobmanagerAdminBundle:Formation:index }

admin_formation_view:
    path: /formation/{id}
    defaults: { _controller: JobmanagerAdminBundle:Formation:view }

admin_formation_create:
    pattern: /formation-create
    defaults: { _controller: JobmanagerAdminBundle:Formation:create }

admin_formation_edit:
    path: /formation-edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:Formation:edit }
    requirements:
        id: \d+

admin_formation_delete:
    path: /formation-delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:Formation:delete }
    requirements:
        id: \d+
        
        
# jobexperience CRUD

admin_jobexperience_index:
    pattern: /jobexperience
    defaults: { _controller: JobmanagerAdminBundle:JobExperience:index }

admin_jobexperience_view:
    path: /jobexperience/{id}
    defaults: { _controller: JobmanagerAdminBundle:JobExperience:view }

admin_jobexperience_create:
    pattern: /jobexperience-create
    defaults: { _controller: JobmanagerAdminBundle:JobExperience:create }

admin_jobexperience_edit:
    path: /jobexperience-edit/{id}
    defaults: { _controller: JobmanagerAdminBundle:JobExperience:edit }
    requirements:
        id: \d+

admin_jobexperience_delete:
    path: /jobexperience-delete/{id}
    defaults: { _controller: JobmanagerAdminBundle:JobExperience:delete }
    requirements:
        id: \d+