parameters:
#    jobmanager_admin.example.class: Jobmanager\AdminBundle\Example

services:
    jobmanager_admin.jobimport:
        class: Jobmanager\AdminBundle\Service\JobImport
        arguments: [ @doctrine.orm.entity_manager ]
