parameters:
#    jobmanager_admin.example.class: Jobmanager\AdminBundle\Example

services:
#    jobmanager_admin.example:
#        class: %jobmanager_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
