parameters:
#    jobmanager_admin.example.class: Jobmanager\AdminBundle\Example

services:
    jobmanager_admin.jobimport:
        class: Jobmanager\AdminBundle\Service\JobImport
        arguments: [ @doctrine.orm.entity_manager ]

    jobmanager_admin.form_to_entity:
            class: Jobmanager\AdminBundle\Service\FormToEntity
            arguments: [ @doctrine.orm.entity_manager ]