<?php

namespace Jobmanager\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CandidateJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidateJobRepository extends EntityRepository
{
    public function getCandidateJobByDateInv()
    {
        $qb =$this->createQueryBuilder('cj');

        $qb->orderBy('cj.createdDate', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
