<?php

namespace Jobmanager\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function getCompanyByIdInv()
    {
        $qb = $this->createQueryBuilder('c');

        $qb->orderBy('c.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
