<?php

namespace Jobmanager\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FonecallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonecallRepository extends EntityRepository
{
    public function getFonecallByDate()
    {
        $qb = $this->createQueryBuilder('f');

        $qb->orderBy('f.dateBegin', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
