<?php

namespace Jobmanager\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FonecallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonecallRepository extends EntityRepository
{
    public function getFonecallByDate()
    {
        $qb = $this->createQueryBuilder('f');

        $qb->orderBy('f.dateBegin', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function checkIfCandidateJobHasFonecall($candidateJob)
    {
        $qb = $this->createQueryBuilder('f');

        $qb
            ->addSelect('f')
            ->where('f.candidate_job = :id')
            ->setParameter('id', $candidateJob)
        ;

        $result = $qb->getQuery()->getResult();

        // check if result
        if ($result != null) {
            return true;
        } else {
            return false;
        }
    }


}
