<?php

namespace Jobmanager\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingRepository extends EntityRepository
{
    public function getMeetingsByDate()
    {
        $qb = $this->createQueryBuilder('m');

        $qb
            ->orderBy('m.dateBegin', 'DESC')
        ;

        return $qb->getQuery()->getResult();
    }
}
