<?php

namespace Jobmanager\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotivationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivationRepository extends EntityRepository
{
    public function getLastMotivationFromCandidate($id)
    {
        $qb = $this->createQueryBuilder('m');

        $qb
            ->addSelect('m')
            ->join('m.candidate', 'c')
            ->where('c.id = :id')
            ->setParameter('id', $id)
        ;

        return $qb->getQuery()->getResult();
    }
}
