<?php

namespace Jobmanager\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecallRepository extends EntityRepository
{
    public function getNewRecalls()
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->addSelect('r')
            ->where('r.isRecalled = :isRecalled')
            ->setParameter('isRecalled', 0)
        ;

        return $qb->getQuery()->getResult();
    }

    public function getNewRecallsRecruiterCompany()
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->addSelect('r')
            ->leftJoin('r.recruiter', 're')
            ->addSelect('re')
            ->leftJoin('re.company', 'c')
            ->addSelect('c')
            ->where('r.isRecalled = :isRecalled')
            ->setParameter('isRecalled', 0)
            ->orderBy('r.createdDate', 'DESC')
        ;

        return $qb->getQuery()->getResult();
    }

    public function getRecallsRecruiterCompany()
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->addSelect('r')
            ->leftJoin('r.recruiter', 're')
            ->addSelect('re')
            ->leftJoin('re.company', 'c')
            ->addSelect('c')
            ->orderBy('r.createdDate', 'DESC')
        ;

        return $qb->getQuery()->getResult();
    }
}
