<?php

namespace Jobmanager\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecruiterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruiterRepository extends EntityRepository
{
    public function getRecruitersByIdInv()
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->orderBy('r.id', 'DESC')
        ;

        return $qb->getQuery()->getResult();
    }
}
