Company:
    type: entity
    table: company
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        address:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        zip:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        city:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        country:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        urlCompany:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: url_company
    lifecycleCallbacks: {  }
