Job:
    type: entity
    table: job
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdDate:
            type: datetime
            nullable: false
            comment: ''
            column: created_date
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        urlJob:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: url_job
    lifecycleCallbacks: {  }
