parameters:
#    jobmanager_user.example.class: Jobmanager\UserBundle\Example

services:
#    jobmanager_user.example:
#        class: %jobmanager_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
